version: '3'
services:
  web:
    container_name: gatsby
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "gatsby develop --host 0.0.0.0"
    volumes:
      - /app/node_modules
      - ./app:/app
